#数据库
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/demo
    username: root
    password: 77889900@
    driver-class-name: com.mysql.cj.jdbc.Driver

  thymeleaf:
    cache: false
    mode: LEGACYHTML5